# Generated by Django 2.1.5 on 2020-01-05 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plotz', '0001_initial'),
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular plot in the system', primary_key=True, serialize=False)),
                ('reciept_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('reciept_number', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_balance', models.IntegerField()),
                ('amount_paid', models.CharField(blank=True, max_length=200, null=True)),
                ('current_balance', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('reciept_date', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('plot_number', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='plotz.Plot')),
            ],
        ),
    ]
