# Generated by Django 2.1.5 on 2019-08-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
