# Generated by Django 2.1.5 on 2019-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20190822_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_e',
            field=models.ManyToManyField(help_text='Select machine and equipmens', to='machines.Machine_e'),
        ),
    ]
