# Generated by Django 2.1.5 on 2019-01-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
    ]
