# Generated by Django 2.1.5 on 2019-01-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190126_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Plot_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mpesamessage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reciept_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reciept_no',
        ),
    ]
