# Generated by Django 2.1.5 on 2019-01-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malipo',
            name='Previouspayment',
        ),
        migrations.DeleteModel(
            name='Previouspayment',
        ),
    ]
