# Generated by Django 2.1.5 on 2019-01-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0002_auto_20190126_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malipo',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
