# Generated by Django 2.1.5 on 2019-02-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0004_kalipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalipo',
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='kalipo',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='kalipo',
            name='Realtor',
        ),
        migrations.RemoveField(
            model_name='kalipo',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='kalipo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='malipo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Kalipo',
        ),
    ]
