# Generated by Django 2.1.5 on 2019-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0008_auto_20190203_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='malipo',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_eight',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_eleven',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_five',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_four',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_nine',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_seven',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_six',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_ten',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_three',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_twelve',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malipo_two',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
