# Generated by Django 2.1.5 on 2019-08-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={},
        ),
    ]
