# Generated by Django 2.1.5 on 2019-01-18 16:03

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('payment_plan', models.CharField(max_length=200)),
                ('water', models.CharField(max_length=100)),
                ('roads', models.CharField(max_length=100)),
                ('electricity', models.CharField(max_length=100)),
                ('plot_type', models.CharField(max_length=100)),
                ('lot_size', models.CharField(max_length=100)),
                ('sqft', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('item_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
