# Generated by Django 2.1.5 on 2019-04-29 15:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, help_text='particular name of the area as known to the locals', max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('payment_plan', models.CharField(choices=[('1', 'Cash'), ('2', 'Installments'), ('3', 'Negotiable')], help_text='mode of payment required', max_length=200)),
                ('water', models.CharField(choices=[('1', '50m+'), ('2', '250m+'), ('3', '500+'), ('4', '750m+'), ('5', '1000m+'), ('6', 'none')], help_text='the distance from water pipe or source', max_length=100)),
                ('roads', models.CharField(choices=[('1', 'tarmac'), ('2', 'gravel'), ('3', 'seasonal'), ('4', 'maram')], help_text='what the main road to the area is made of', max_length=100)),
                ('electricity', models.CharField(choices=[('1', '50m+'), ('2', '250m+'), ('3', '500+'), ('4', '750m+'), ('5', '1000m+'), ('6', 'none')], help_text='distance from the closest transformer', max_length=100)),
                ('plot_type', models.CharField(choices=[('1', 'Commercial'), ('2', 'Residential'), ('3', 'Farm'), ('4', 'lease')], max_length=100)),
                ('plot_size', models.CharField(choices=[('1', '40X80ft Approx'), ('2', '50X100ft Approx'), ('3', '100X100ft Approx'), ('3', '1 Acre'), ('4', '2 Acre'), ('5', '3 Acre'), ('6', '4 Acre'), ('7', '5 Acre'), ('8', '6 Acre'), ('7', '7 Acre'), ('8', '8 Acre'), ('9', '9 Acre'), ('10', '10 Acre'), ('11', '100+ Acre')], max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, null=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
