# Generated by Django 2.1.5 on 2019-01-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='item_1',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_2',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_3',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_4',
            new_name='photo_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_5',
            new_name='photo_5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_6',
            new_name='photo_6',
        ),
    ]
