# Generated by Django 2.1.5 on 2019-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='electricity',
            field=models.CharField(help_text='distance from the closest transformer', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='payment_plan',
            field=models.CharField(help_text='mode of payment required', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plot_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plot_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='roads',
            field=models.CharField(help_text='what the main road to the area is made of', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='water',
            field=models.CharField(help_text='the distance from water pipe or source', max_length=100),
        ),
    ]
