# Generated by Django 2.1.5 on 2020-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
