# Generated by Django 2.1.5 on 2020-01-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_prime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_prime',
            new_name='is_mvp',
        ),
    ]
