# Generated by Django 2.1.5 on 2019-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190127_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_header', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_page', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_footer', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
