# Generated by Django 2.1.5 on 2019-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_photoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photoa',
        ),
    ]
