# Generated by Django 2.1.5 on 2020-01-08 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_auto_20200106_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
