# Generated by Django 2.1.5 on 2020-01-09 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
