# Generated by Django 2.1.5 on 2019-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='image',
        ),
        migrations.AddField(
            model_name='logo',
            name='kwela',
            field=models.ImageField(default='kwela.jpg', upload_to='logo_pics'),
        ),
    ]
