# Generated by Django 2.1.5 on 2019-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190215_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='kwela',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
