# Generated by Django 2.1.5 on 2019-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190215_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='kwela',
            field=models.ImageField(blank=True, null=True, upload_to='logo_pics'),
        ),
    ]
