# Generated by Django 2.1.5 on 2019-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190216_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='kwela',
            field=models.ImageField(default='default.jpg', upload_to='kwela_pics'),
        ),
    ]
