# Generated by Django 2.1.5 on 2019-03-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20190216_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
