# Generated by Django 2.1.5 on 2019-12-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('team', '0002_auto_20191216_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
