# Generated by Django 2.1.5 on 2019-12-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191216_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
    ]
