# Generated by Django 2.1.5 on 2019-02-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoa',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photoi',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
