# Generated by Django 2.1.5 on 2019-09-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190912_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='header',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
