# Generated by Django 2.1.5 on 2019-02-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190202_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='Realtor',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
