# Generated by Django 2.1.5 on 2019-12-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190827_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_made',
        ),
        migrations.RemoveField(
            model_name='account',
            name='property_bought',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='property_bought',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='property_bought',
        ),
        migrations.RemoveField(
            model_name='property_id',
            name='Location',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Property_id',
        ),
    ]
