# Generated by Django 2.1.5 on 2019-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasifu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasifu',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='wasifu_pics'),
        ),
    ]
