# Generated by Django 2.1.5 on 2019-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190201_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
