# Generated by Django 2.1.5 on 2019-03-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
