# Generated by Django 2.1.5 on 2019-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='logo',
            new_name='photo_1',
        ),
    ]
