# Generated by Django 2.1.5 on 2019-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msuppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msupplier',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
