# Generated by Django 2.1.5 on 2019-09-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
