# Generated by Django 2.1.5 on 2019-05-01 09:53

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='e.g property history, ownership, development')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_BMVP', models.BooleanField(default=False)),
                ('Registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer registered', null=True)),
                ('Deposit_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer paid deposit', null=True)),
                ('deposit_amount_paid', models.IntegerField(blank=True, help_text='amount paid as deposit', null=True)),
                ('amount_agreed_on', models.IntegerField(blank=True, help_text='amount agreed on as buying price', null=True)),
                ('installment_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer agrees to pay next installment', null=True)),
                ('Buying_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer bought the property or finished paying for the property', null=True)),
            ],
            options={
                'permissions': (('can_view_buyer', 'Set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='ignore location if it already exists on listing, Only enter a new Location (e.g. Ruiru, Mwea, e.t.c)', max_length=200, null=True)),
                ('propertiesno', models.IntegerField(blank=True, help_text='number of properties in this specific area', null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='define how many plots are what size, area history')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='e.g property history, ownership, development')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('Registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer registered')),
                ('listingAgreement_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer registered')),
                ('selling_price', models.IntegerField(blank=True, help_text='amount agreed on as selling price', null=True)),
                ('commissions', models.IntegerField(blank=True, help_text='amount agreed on as commisions to realtor', null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Paymenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of payment choosen by the client (e.g. Cash, 3 months installments, 6 months installments e.t.c)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', ckeditor.fields.RichTextField(help_text='Enter a brief description of the property ownership', max_length=1000)),
                ('Paymenttype', models.ManyToManyField(help_text='select payment method', to='catalog.Paymenttype')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Propertytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of plot (e.g. Commercial Plot, Rent house, e.t.c)', max_length=200)),
            ],
        ),
    ]
