# Generated by Django 2.1.5 on 2019-01-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190120_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Owner'),
        ),
    ]
