# Generated by Django 2.1.5 on 2019-01-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_propertyinstance_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinstance',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='propertyinstance',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyInstance',
        ),
    ]
