# Generated by Django 2.1.5 on 2019-01-20 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190120_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='amount_agreed_on',
            field=models.IntegerField(blank=True, help_text='amount agreed on as buying price', null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='deposit_amount_paid',
            field=models.IntegerField(blank=True, help_text='amount paid as deposit', null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='commissions',
            field=models.IntegerField(blank=True, help_text='amount agreed on as commisions to realtor', null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='selling_price',
            field=models.IntegerField(blank=True, help_text='amount agreed on as selling price', null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='installment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer agrees to be paying installments'),
        ),
    ]
