# Generated by Django 2.1.5 on 2019-01-20 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190120_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Buying_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer bought the property or finished paying for the property', null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='Deposit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer paid deposit', null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='Registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer registered', null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='installment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when buyer agrees to pay next installment', null=True),
        ),
    ]
