# Generated by Django 2.1.5 on 2019-01-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190120_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='propertiesno',
            field=models.IntegerField(blank=True, help_text='number of properties in this specific area', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text='ignore location if it already exists on listing, Only enter a new Location (e.g. Ruiru, Mwea, e.t.c)', max_length=200, null=True),
        ),
    ]
