# Generated by Django 2.1.5 on 2019-01-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190121_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'permissions': (('can_view_buyer', 'Set book as returned'),)},
        ),
    ]
