# Generated by Django 2.1.5 on 2019-12-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_expected', models.IntegerField(help_text='total payment expected from all properties bought', null=True)),
                ('deposit_paid', models.IntegerField(blank=True, null=True)),
                ('total_payments', models.IntegerField(null=True)),
                ('total_balance', models.IntegerField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=200, null=True)),
                ('property_price_tag', models.CharField(max_length=200, null=True)),
                ('available', models.BooleanField(blank=True, default=False, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('property_of_interest', models.ManyToManyField(help_text='all properties bought by buyer', to='records.Property_id')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='property_bought',
            field=models.ManyToManyField(help_text='all properties bought by buyer', to='records.Property_id'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='property_bought',
            field=models.ManyToManyField(help_text='all properties bought by buyer', to='records.Property_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='buyer',
            field=models.ManyToManyField(help_text='Select The Buyer', to='records.Buyer'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_made',
            field=models.ManyToManyField(help_text='Select your payments made so far', to='records.Payment'),
        ),
        migrations.AddField(
            model_name='account',
            name='property_bought',
            field=models.ManyToManyField(help_text='Select your properties', to='records.Property_id'),
        ),
    ]
