# Generated by Django 2.1.5 on 2019-03-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='ministry_name',
        ),
    ]
