# Generated by Django 2.1.5 on 2019-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190916_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
